version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:15.2.1
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test

workflows:
  test:
    jobs:
      - test
